# Conda Environment Setup Instructions
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name data_visualisation > environment.yml
#    conda env remove --name data_visualisation
#    conda env list

name: data_visualisation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - pip:
      - ipykernel==6.17.1
      - ipython==8.7.0
      - jupyter-client==7.4.7
      - jupyter-core==5.1.0
      - scipy==1.9.3
      - scikit-learn==1.2.0
