name: data_visualization
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - prophet
  - xgboost
  - shap
  - statsmodels
  - pip:
      - ipykernel
      - ipython
      - jupyter-client
      - jupyter-core
      - scipy
      - scikit-learn