name: data_visualisation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - prophet
  - xgboost
  - shap
  - statsmodels
  - pip:
      - ipykernel==6.17.1
      - ipython==8.7.0
      - jupyter-client==7.4.7
      - jupyter-core==5.1.0
      - scipy==1.9.3
      - scikit-learn==1.2.0